meta_product_name: "Booze Hounds"
meta_title: "BoozeHounds - Boozers for you and your hound"
meta_description: "An app to help you find the best pub to go to for you and your dog, allows you to put in your postcode and see pubs near you then filter by things such as garden and pool table"
meta_image: "doggos.webp"
